### ISSUE TITLE
Indicate whether it's ready for use in production

### ISSUE THREAD

**Issue by terales** [nulpunkt/yesql-php#2]
Hello! Thanks a lot for open sourcing your port!

In the README you're stating:
> I'm trying to build a clone of the wonderful yesql library from clojure. The idea is to have a seperate sql file for queries, which you can then access as methods on a class.

I'm a bit confused by this statement. Is it ready for use in production? Can you specify this in the README, please?

**Comment by nulpunkt** [comment]
Oh man, I had to give this some serious thought!

The story is this: I built for fun on a friday, liked a lot and now we are using it where I work. So I guess it's production ready. I'll see if I can word it more clearly in the README! Thanks for the feedback.

If there are anything in particular you'd like to know before using it in production, I'd love to know, so I can address it.

**Comment by terales** [comment]
> we are using it where I work

That's all I need. Now I know that at least someone use it in production :)
Do you need PR to update a README?

**Comment by nulpunkt** [comment]
If you have a good wording I'll happily accept a pr, so I don't have to write it myself :)
