### ISSUE TITLE
Add titles to the examples in the README

### ISSUE THREAD

**Issue by terales** [nulpunkt/yesql-php#6]
As @nulpunkt asked in https://github.com/nulpunkt/yesql-php/issues/5#issuecomment-366642404:
> The readme is getting longer, so it would be cool with ideas on how to improve it!

I don't mind long README, but I see it as a very useful feature. With long README you can search on the page with a browser and without any code. Consider example:
https://github.com/avajs/ava

The only thing we need to have a useful long README is to add the Contents section. To make it more readable we need to add titles to the examples.

**Comment by nulpunkt** [comment]
This is a great idea for improving the README!

**Comment by nulpunkt** [comment]
Just added titles, let me know if they suck too much :)

**Comment by terales** [comment]
They are awesome!
Thanks a lot!

**Comment by nulpunkt** [comment]
Thanks! :smile:
